# Waypoints describe the desired motion trajectory:
#  - time [s]: can be either a single value or an interval for which joint_positions hold
#  - joint_positions:
#     - hand closure [0,1].

waypoints:
  -
    time: [1.0]
    joint_positions:
      qbhand: [0.0]
  -
    time: [2.25, 2.75]
    joint_positions:
      qbhand: [0.7]
  -
    time: [4.0, 5.0]
    joint_positions:
      qbhand: [0.0]
  -
    time: [10.75, 11.25]
    joint_positions:
      qbhand: [0.7]
  -
    time: [17.0, 18.0]
    joint_positions:
      qbhand: [0.0]