$(arg device_name)_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# control the qbhand motor and its relative synergy
$(arg device_name)_synergy_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg device_name)_synergy_joint
  constraints:  # fake values due to the adaptability
    goal_time: 10.0
    stopped_velocity_tolerance: 10.0
    $(arg device_name)_synergy_joint:
      trajectory: 10.0
      goal: 10.0
  state_publish_rate: 100
  action_monitor_rate: 120
  stop_trajectory_duration: 0