# This YAML file must contains the configuration of each mesh to properly build the URDF automagically.
# The aim of this additional file is to encapsulate all the physical properties in a single place without hiding them
# in a long URDF structure.
#
# Note: there is no need to modify this file unless you hack the qbhand physical mechanism. Nonetheless it is
#       recommended to create a distinct YAML file for each version of the qbhand (this helps with versioning and
#       leaves the default configuration as is).
#
# Brief description:
# * The `default` group holds the anchors for the common default settings, i.e. avoid annoying repetitions.
# * The `qb_hand_<left/right>` group contains the current properties to build the URDF correctly.

default:
  parameters:
    axis_abduction: &axis_abduction "0 0 -1"
    axis_flexion: &axis_flexion "0 0 -1"
    dynamics: &dynamics
      damping: 0.0
      friction: 0.0
    effort_limit: &effort 100
    velocity_limit: &velocity 100
    virtual_mechanism: &virtual_mechanism
      position: "0.013 0 0"
      orientation: "0 0 0"
    single_synergy: &single_synergy
      axis: "0 0 1"  # it is not important though
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 1.0
        effort: *effort
        velocity: *velocity
    inertial: &phalanx_inertial
      mass: 0.01
      origin: "0 0 0"
      inertia:
        ixx: 0.000001
        ixy: 0.0
        ixz: 0.0
        iyy: 0.000001
        iyz: 0.0
        izz: 0.000001

  finger:
    knuckle: &knuckle
      mesh: "ph_knuckle"
      mesh_collision: "ph_knuckle"
      # 'position' and 'orientation' should be specified each time
      position: "0 0 0"
      orientation: "0 0 0"
      axis: *axis_abduction
      mimic_reduction: 0.0
      dynamics: *dynamics
      limits:
        lower: -0.524
        upper: 0.524
        effort: *effort
        velocity: *velocity
      inertial: *phalanx_inertial

    medium: &medium
      mesh: "ph_medium"
      mesh_collision: "ph_medium"
      position: "0.017 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 0.785
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 0.785
        effort: *effort
        velocity: *velocity
      inertial: *phalanx_inertial

    medium_after_knuckle: &medium_after_knuckle
      << : *medium
      position: "0 0.009 0"
      orientation: "1.57 0 1.57"

    small: &small
      mesh: "ph_small"
      mesh_collision: "ph_small"
      position: "0.009 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 0.785
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 0.785
        effort: *effort
        velocity: *velocity
      inertial: *phalanx_inertial

    small_after_knuckle: &small_after_knuckle
      << : *small
      position: "0 0.009 0"
      orientation: "1.57 0 1.57"

    small_after_medium: &small_after_medium
      << : *small
      position: "0.017 0 0"
      orientation: "0 0 0"

    distal: &distal
      mesh: "ph_distal"
      mesh_collision: "ph_distal"
      position: "0.009 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 0.785
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 0.785
        effort: *effort
        velocity: *velocity
      inertial: *phalanx_inertial


qbhand_right:
  base:
    mesh: "flange_iso_04"
    mesh_collision: "flange_iso_04"
    inertial:
      mass: 0.150
      origin: "0 0 0.0015"
      inertia:
        ixx: 0.00006
        ixy: 0
        ixz: 0
        iyy: 0.00006
        iyz: 0
        izz: 0.00009

  palm:
    mesh: "palm_pinch_r"
    mesh_collision: "palm_pinch_r"
    position: "-0.0045 0.0145 0.144"
    orientation: "1.57 0 0"
    inertial:
      mass: 0.360
      origin: "0.0 0.02 0.05"
      inertia:
        ixx: 0.00045
        ixy: 0.0
        ixz: 0.0
        iyy: 0.00060
        iyz: 0.0
        izz: 0.00025

  synergy: *single_synergy

  # all fingers have the same base structure and only few things change among them (e.g. the pose of the knuckle)
  thumb:
    knuckle:
      << : *knuckle
      mesh: "ph_thumb_r"
      mesh_collision: "ph_thumb_r"
      position: "-0.0435 -0.0435 -0.002"
      orientation: "-1.57 3.14 0"
      mimic_reduction: 2.542
      limits:
        lower: 0.0
        upper: 1.571
        effort: *effort
        velocity: *velocity
    proximal:
      << : *small
      position: "0.0255 -0.004 -0.0025"
      orientation: "-1.15 0.0 0.0"
    distal: *distal

  index:
    knuckle:
      << : *knuckle
      position: "-0.02 -0.007 0.014"
      orientation: "0 0 0"
      mimic_reduction: -0.2
    proximal: *medium_after_knuckle
    middle: *small_after_medium
    distal: *distal

  middle:
    knuckle:
      << : *knuckle
      position: "0 0 0.014"
      orientation: "0 0 0"
      mimic_reduction: 0.0
    proximal: *medium_after_knuckle
    middle: *small_after_medium
    distal: *distal

  ring:
    knuckle:
      << : *knuckle
      position: "0.02 -0.007 0.014"
      orientation: "0 0 0"
      mimic_reduction: 0.2
    proximal: *medium_after_knuckle
    middle: *small_after_medium
    distal: *distal

  little:
    knuckle:
      << : *knuckle
      position: "0.04 -0.012 0.014"
      orientation: "0 0 0"
      mimic_reduction: 0.4
    proximal: *small_after_knuckle
    middle: *small
    distal: *distal


qbhand_left:
  base:
    mesh: "flange_iso_04"
    mesh_collision: "flange_iso_04"
    inertial:
      mass: 0.150
      origin: "0 0 0.0015"
      inertia:
        ixx: 0.00006
        ixy: 0
        ixz: 0
        iyy: 0.00006
        iyz: 0
        izz: 0.00009

  palm:
    mesh: "palm_pinch_l"
    mesh_collision: "palm_pinch_l"
    position: "0.0045 0.0145 0.144"
    orientation: "1.57 0 3.14"
    inertial:
      mass: 0.360
      origin: "0.0 0.02 0.05"
      inertia:
        ixx: 0.00045
        ixy: 0.0
        ixz: 0.0
        iyy: 0.00060
        iyz: 0.0
        izz: 0.00025

  synergy: *single_synergy

  # all fingers have the same base structure and only few things change among them (e.g. the pose of the knuckle)
  thumb:
    knuckle:
      << : *knuckle
      mesh: "ph_thumb_l"
      mesh_collision: "ph_thumb_l"
      position: "-0.0435 -0.0435 -0.002"
      orientation: "1.57 3.14 0"
      mimic_reduction: 2.542
      limits:
        lower: 0.0
        upper: 1.571
        effort: *effort
        velocity: *velocity
    proximal:
      << : *small
      position: "0.0255 -0.004 0.0025"
      orientation: "1.15 0.0 0.0"
    distal: *distal

  index:
    knuckle:
      << : *knuckle
      position: "-0.02 -0.007 -0.014"
      orientation: "0 3.14 0"
      mimic_reduction: 0.2
    proximal: *medium_after_knuckle
    middle: *small_after_medium
    distal: *distal

  middle:
    knuckle:
      << : *knuckle
      position: "0 0 -0.014"
      orientation: "0 3.14 0"
      mimic_reduction: 0.0
    proximal: *medium_after_knuckle
    middle: *small_after_medium
    distal: *distal

  ring:
    knuckle:
      << : *knuckle
      position: "0.02 -0.007 -0.014"
      orientation: "0 3.14 0"
      mimic_reduction: -0.2
    proximal: *medium_after_knuckle
    middle: *small_after_medium
    distal: *distal

  little:
    knuckle:
      << : *knuckle
      position: "0.04 -0.012 -0.014"
      orientation: "0 3.14 0"
      mimic_reduction: -0.4
    proximal: *small_after_knuckle
    middle: *small
    distal: *distal